version: '3.8'

services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    expose:
      - 9000
    depends_on:
      - mysql

  nginx-backend:
    image: nginx:alpine
    volumes:
      - ./backend:/var/www/html
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
